### PR TITLE
Update 2017.2

### PR DESCRIPTION
**Pull request by joedborg**

### CODE REVIEW

**Comment by joedborg** [comment]
Ping @evandandrea, could we do the same as we did for the pro version please?

Many thanks!
Joe

**Comment by evandandrea** [comment]
Looks good! Thanks Joe.

**Comment by evandandrea** [comment]
@joedborg could you give edge a test? If you're happy, I'll promote this to stable.

**Comment by joedborg** [comment]
@evandandrea it looks good, please promote it.  Thanks!

**Comment by evandandrea** [comment]
@joedborg bumped to stable. Can you confirm that works?

**Comment by joedborg** [comment]
@evandandrea yeah it's working, many thanks!

**Pull request merged**
